### ISSUE TITLE
AttributeError: 'Operator' object has no attribute 'is_geometric_action'

### ISSUE THREAD

**Issue by sl148** [kh11kim/tree4tamp#1]
Hello,

Thank you for sharing the code. 
I've attempted to execute your test files, but encountered an issue. The error message I received states, **"AttributeError: 'Operator' object has no attribute 'is_geometric_action'."** 
Could you possibly shed some light on why this error might be occurring and suggest any possible solutions? Thanks in advance!

I've included the complete error codes below for your review:

----Planning start----
Traceback (most recent call last):
  File "test/test_nonmono.py", line 9, in <module>
    states, commands = tree.plan(state_init)
  File "/home/lee/Downloads/ee/test/tree4tamp/planner/tamp_planner.py", line 34, in plan
    self.task_planning_layer()
  File "/home/lee/Downloads/ee/test/tree4tamp/planner/tamp_planner.py", line 52, in task_planning_layer
    rewards = self.subgoal_sampling_layer(pi, art_node_seq)
  File "/home/lee/Downloads/ee/test/tree4tamp/planner/tamp_planner.py", line 74, in subgoal_sampling_layer
    batch_atts = self.ss.sample_batch_atts_with_last_mode(pi, state_goal.mode)
  File "/home/lee/Downloads/ee/test/tree4tamp/planner/subgoal_sampler.py", line 24, in sample_batch_atts_with_last_mode
    if not a.is_geometric_action():
AttributeError: 'Operator' object has no attribute 'is_geometric_action'

**Comment by sl148** [comment]
Actually, I found out that the error was due to the different version of pyperplan.
